In [1]:
import numpy as np

In [4]:
np.mgrid[3:5, 3:6, 2:5]

array([[[[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],

        [[4, 4, 4],
         [4, 4, 4],
         [4, 4, 4]]],


       [[[3, 3, 3],
         [4, 4, 4],
         [5, 5, 5]],

        [[3, 3, 3],
         [4, 4, 4],
         [5, 5, 5]]],


       [[[2, 3, 4],
         [2, 3, 4],
         [2, 3, 4]],

        [[2, 3, 4],
         [2, 3, 4],
         [2, 3, 4]]]])

In [9]:
np.ogrid[3:5,3:6,2:5]

[array([[[3]],
 
        [[4]]]),
 array([[[3],
         [4],
         [5]]]),
 array([[[2, 3, 4]]])]

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
arr = np.random.randint(3,34,20)
np.bincount(arr)

array([0, 0, 0, 0, 2, 0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 1, 0, 0, 3, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 3])

In [68]:
arr

array([ 8, 10, 20,  9, 30, 22, 27, 30, 16, 20,  6, 20, 24,  4, 11,  6, 16,
       30, 17,  4])

In [80]:
arr[-4:]

array([16, 30, 17,  4])

In [96]:
np.random.randint(3,34,(20,4,2)).reshape(8,-1).reshape(-1,).shape

(160,)

In [111]:
np.random.randint(3,34,(20,4,2))[:2,:,:]

array([[[ 8,  8],
        [17, 16],
        [ 5, 11],
        [28,  3]],

       [[30,  8],
        [ 4, 24],
        [33, 19],
        [13,  7]]])

In [112]:
arr = np.random.randint(3,34,(20,4,2))

In [116]:
np.sum(arr,axis=0).shape

(4, 2)

In [118]:
np.sum(arr,axis=(0,2)).shape

(4,)

In [120]:
np.sum(arr,axis=(0,1,2))

2927

In [126]:
np.eye(4) @ np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [133]:
np.matmul(np.eye(4), np.eye(4,5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [137]:
np.dot(np.random.randint(0,20,(2,4)), np.random.randint(0,20,(4,10))).shape

(2, 10)

In [146]:
np.arange(4).reshape(2,2) * np.eye(2)

array([[0., 0.],
       [0., 3.]])

In [158]:
am = np.argmax(arr,axis=0)
am

array([[ 2, 11],
       [17,  1],
       [ 1,  8],
       [ 9,  0]])

In [163]:
bc = np.bincount(am.flatten())
ix = np.argmax(bc) == am
ix

array([[False, False],
       [False,  True],
       [ True, False],
       [False, False]])

In [200]:
from scipy.sparse import coo_matrix

dm = coo_matrix(ix)
dm

<4x2 sparse matrix of type '<class 'numpy.bool_'>'
	with 2 stored elements in COOrdinate format>

In [201]:
dm.nonzero()

(array([1, 2], dtype=int32), array([1, 0], dtype=int32))

In [202]:
dm.data

array([ True,  True])

In [203]:
dm.shape

(4, 2)

In [165]:
tf.sparse.SparseTensor(
    indices, values, dense_shape
)

NameError: name 'tf' is not defined

In [204]:
dm.toarray()

array([[False, False],
       [False,  True],
       [ True, False],
       [False, False]])

In [195]:
from scipy.sparse import dia_matrix

dia_matrix(ix).toarray()

array([[False, False],
       [False,  True],
       [ True, False],
       [False, False]])